from flask import render_template
from . import m4_bp

@m4_bp.route('/placement_clustering')
def placement_clustering_page():
    content = r"""
    <p>Unsupervised learning allows us to find hidden structures and segments within our student population without relying on the target labels (PlacementStatus or Salary).</p>
    <p>By clustering the students based entirely on their features (CGPA, Coding Scores, Internships, etc.), we can discover distinct profiles or "personas" that naturally exist on campus.</p>
    """
    
    math_content = r"""
    <p><strong>Connecting Unsupervised to Supervised Learning</strong></p>
    <p>One advanced technique is to use the cluster labels generated by K-Means as a brand new feature for the supervised models (Random Forest, XGBoost).</p>
    <ul>
        <li>If K-Means clusters students into "High Performers", "Average", and "At Risk"...</li>
        <li>We can append a new column <code>Cluster_ID</code> to the dataset.</li>
        <li>The predictive model can now use this engineered macro-level feature to make faster, more accurate predictions.</li>
    </ul>
    """
    
    application_content = r"""
    <p>In our M4 module, we successfully used K-Means to identify 4 distinct student clusters.</p>
    <p>We also implemented Anomaly Detection (Isolation Forest, One-Class SVM) to find "outlier" students. These are students whose profiles are highly unusual (e.g., extremely low CGPA but very high coding test scores). Identifying these outliers is crucial, as they often confuse standard predictive models and might require separate, manual evaluation by the placement cell.</p>
    """

    return render_template(
        'educational_concept.html',
        title="Clustering Summary & Synthesis",
        subtitle="Extracting actionable insights from unlabeled student data.",
        icon="ph ph-intersect-three",
        content=content,
        math_content=math_content,
        application_content=application_content
    )
